version: "3.8"

services:
  app:
    image: local/file_upload_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    container_name: file_upload_app
    ports:
      - "3010:3010"
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/idea_usher_post # Add the MongoDB URL here
      CLAMAV_HOST: clamav
      CLAMAV_PORT: 3310
    depends_on:
      - mongo
      - clamav
    command: npm run dev
  mongo:
      image: mongo:5.0
      container_name: file_upload_db
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
  clamav:
    image: clamav/clamav:latest
    container_name: file_upload_antivirus
    ports:
      - "3310:3310"  # Expose the default ClamAV port
    volumes:
      - ./clamd.conf:/etc/clamav/clamd.conf  # Attach custom config file
      - clamav-data:/var/lib/clamav  # Persist ClamAV data
    environment:
      - CLAMD_SCAN=enabled

volumes:
  mongo-data:
  clamav-data: